// vue/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png" />
    <HelloWorld msg="Welcome to Your Vue.js App" />
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld.vue";

export default {
  name: "App",
  components: {
    HelloWorld
  }
};
</script>

<style src="@esri/calcite-components/dist/calcite/calcite.css"></style>

// react/src/App.js
import React from 'react';
import '@esri/calcite-components/dist/calcite/calcite.css';
import './App.css';

function App() {
  return (
    <div className="App">
      <h1>Hello, React</h1>
      <calcite-button>Test</calcite-button>
      <calcite-icon icon="banana" />
    </div>
  );
}

export default App;
