// angular/src/app/app.component.ts
import { Component } from '@angular/core';

// Calcite Components
import "@esri/calcite-components/dist/components/calcite-button";
import "@esri/calcite-components/dist/components/calcite-icon";
import "@esri/calcite-components/dist/components/calcite-date-picker";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular';
}

<h1>Hello Angular! <calcite-icon icon="banana"></calcite-icon></h1>
<calcite-date-picker></calcite-date-picker>
<calcite-button>My Button</calcite-button>

// react/src/App.js
import React from 'react';
import '@esri/calcite-components/dist/calcite/calcite.css';
import './App.css';

function App() {
  return (
    <div className="App">
      <h1>Hello, React</h1>
      <calcite-button>Test</calcite-button>
      <calcite-icon icon="banana" />
    </div>
  );
}

export default App;
