// react/src/App.tsx
import React, {useState} from 'react';
import {CalciteButton, CalciteIcon, CalciteSlider} from "@esri/calcite-components-react"
import '@esri/calcite-components/dist/calcite/calcite.css';
import './App.css';

function App() {
  const [sliderValue, setSliderValue] = useState<number | null>(50);

  function onUpdate(event: CustomEvent){
    setSliderValue((event.target as HTMLCalciteSliderElement).value);
  }

  return (
    <div className="App">
      <h1>Hello, React</h1>
      <CalciteButton>Test</CalciteButton>
      <CalciteIcon icon="banana" />
      <CalciteSlider
        onCalciteSliderUpdate={onUpdate}
        min={1}
        max={100}
        value={sliderValue}
        step={1} />
      <p>The slider currently has a value of {sliderValue}</p>
    </div>
  );
}

export default App;

// angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "calcite-components-angular-example";
  sliderValue = 50;

  public isLoading: boolean = true;

  ngOnInit() {
    this.fetch();
  }

  async fetch() {
    await new Promise(r => setTimeout(r, 2000));
    this.isLoading = false;
  }

  onSliderInput(event: Event) {
    const value = (event.target as HTMLCalciteSliderElement).value;
    if (typeof value === "number") {
      this.sliderValue = value;
    }
  }

  clearSliderValue() {
    this.sliderValue = 0;
  }
}

<style>
  calcite-icon {
    --calcite-ui-icon-color: #ffe135;
  }
</style>

<div *ngIf="isLoading; else content">
  <calcite-loader label="Loading..."></calcite-loader>
</div>

<ng-template #content>
  <h1>
    Calcite Components Angular Example
    <calcite-icon icon="banana"></calcite-icon>
  </h1>

  <calcite-slider
    min="1"
    max="100"
    [value]="sliderValue"
    (calciteSliderInput)="onSliderInput($event)"
  ></calcite-slider>

  <p>The slider currently has a value of {{ sliderValue }}.</p>

  <calcite-button (click)="clearSliderValue()">Clear</calcite-button>
</ng-template>
